version: "3.8"

services:
  todo_app:
    image: todo_app
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - TEST=${TEST}
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./assets
          target: /app/assets
        - action: sync+restart
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: ./handler
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: rebuild
          path: ./Dockerfile
